### ISSUE TITLE
LICENSE and History

### ISSUE THREAD

**Issue by mrocklin** [dask/daskernetes#11]
I believe that the first commit of this project took heavy inspiration from https://github.com/cedadev/jasmin-dask/blob/master/docker/k8s-adaptive.py , which is currently unlicensed.  We should do a few things:

1.  Verify that we're not currently stealing content.  Are there still significant portions that are copied?
2.  Include a history giving that project and its authors credit, at least for inspiration

cc @yuvipanda @mkjpryor-stfc

**Comment by yuvipanda** [comment]
I agree! I think cleanest thing to do is to make sure we have no significant portions copied & give credit.

**Comment by mkjpryor-stfc** [comment]
Hi both. Thanks for thinking of attributions! As this work was done in my capacity as an STFC employee, I'd need to check if they have a preferred form for attributions. As a publicly-funded research organisation with an open-by-default policy for code, I can't imagine there will be any issues with using the code as a basis.

I'd also like to see @jacobtomlinson and the Met Office Informatics Lab attributed, as my work on the adaptive clusters was influenced a lot by working with them. In fact, k8s-adaptive.py was mostly written in their offices while I was visiting, with significant input from Jacob...!

I'm also happy to contribute where you think I can be useful.

@mrocklin: I assume the intention is for the official Dask Helm chart to consume this package?

**Comment by mrocklin** [comment]
> @mrocklin: I assume the intention is for the official Dask Helm chart to consume this package?

Not necessarily.  This feels a bit more special purpose to me.  Currenly I'm inclined to leave the helm chart as is although I imagine we'll learn more along the way.

**Comment by mrocklin** [comment]
> As a publicly-funded research organisation with an open-by-default policy for code, I can't imagine there will be any issues with using the code as a basis.

It would be nice if the open-by-default policy came with a suggested license (like BSD or Apache) that people could apply automatically as they created repositories.

**Comment by mrocklin** [comment]
> I'm also happy to contribute where you think I can be useful.

A review of the current code would be welcome.  So too would be engagement on any of the current issues.

**Comment by jacobtomlinson** [comment]
Attribution would be great. We are in the position where we are happy to contribute our code in exchange for credit. 

As @mkjpryor-stfc I initially developed the [Jade adaptive script](https://github.com/met-office-lab/jade-dask/blob/master/kubernetes/adaptive.py) which he then evolved into `k8s-adaptive.py` while visiting us last year. It has been my intention to switch to that one ever since but things have gotten in the way.

I appreciate our repo is also unlicensed, however the most permissive license we've been allowed to use so far is LGPL and I doubt you'd be interested in that. Approval for BSD-3 is working its way through here so once that's done we should be able to stick that on.

I think a really good next step would be to take the helm chart we created for Jade and the one Matt created and fuse them together in https://github.com/dask/helm-chart to replace what is currently there. I'm going to start looking at this today.

**Comment by niallrobinson** [comment]
see the new BSD license on https://github.com/met-office-lab/jade-dask

@mkjpryor-stfc I guess the ball's in your court to percolate this through to Pangeo now?

**Comment by mrocklin** [comment]
> Attribution would be great. We are in the position where we are happy to contribute our code in exchange for credit.

Noted.  I'll be giving a couple of talks in the next week.  Is there a standard logo and links that I should use?  I enjoyed our chat last time.  We should maybe check in again sometime soon.

**Comment by jacobtomlinson** [comment]
[This](https://github.com/met-office-lab/blog/blob/master/img/mo-logo.svg) is the one we use on [our website](http://www.informaticslab.co.uk/).

Yes we definitely should! Perhaps next week sometime?
